"""
LLM Provider Manager - Manages multiple LLM providers with automatic fallback.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

from ..config import settings

from .provider import BaseLLMProvider, LLMProvider

log = logging.getLogger("nova.llm.manager")


class LLMManager:
    """
    Manages LLM providers with automatic fallback.

    Provider priority modes:
    - Development: Ollama (optional, local) → Rule Engine fallback
    - Production:  OpenRouter (free cloud) → Gemini Flash (Google API)
    """

    def __init__(self, dev_mode: bool = True) -> None:
        self._providers: List[BaseLLMProvider] = []
        self._current_provider: Optional[BaseLLMProvider] = None
        self._initialized = False
        self._dev_mode = dev_mode

    def initialize(self) -> bool:
        """Initialize all enabled providers in priority order based on mode."""
        if self._initialized:
            return True

        self._providers.clear()

        if self._dev_mode:
            # Development mode: Ollama optional, then rules fallback
            self._init_dev_providers()
        else:
            # Production mode: OpenRouter -> Gemini
            self._init_prod_providers()

        self._initialized = True

        if not self._providers:
            if self._dev_mode:
                log.info("No LLM providers available in dev mode - will use rule engine")
            else:
                log.warning("No LLM providers available in prod mode!")
            return False

        log.info("LLM Manager initialized (%s) with %d providers: %s",
                 "dev" if self._dev_mode else "prod",
                 len(self._providers), [p.name for p in self._providers])
        return True

    def _init_dev_providers(self) -> None:
        """Initialize providers for development mode."""
        # Ollama (local, optional - never blocks)
        if settings.llm_use_ollama:
            try:
                from .ollama_client import OllamaClient

                ollama = OllamaClient(
                    model=settings.llm_ollama_model,
                    base_url=settings.llm_ollama_base_url,
                )
                if ollama.initialize():
                    self._providers.append(ollama)
                    log.info("Ollama provider initialized: %s", settings.llm_ollama_model)
                else:
                    log.debug("Ollama not available (optional in dev mode)")
            except Exception as exc:
                log.debug("Ollama provider unavailable: %s", exc)

    def _init_prod_providers(self) -> None:
        """Initialize providers for production mode."""
        # 1. OpenRouter (free cloud models)
        if settings.llm_use_openrouter:
            try:
                from .openrouter_client import OpenRouterClient

                openrouter = OpenRouterClient(
                    api_key=settings.llm_openrouter_api_key,
                    model=settings.llm_openrouter_model,
                )
                if openrouter.initialize():
                    self._providers.append(openrouter)
                    log.info("OpenRouter provider initialized: %s", settings.llm_openrouter_model)
                else:
                    log.warning("OpenRouter provider failed to initialize")
            except Exception as exc:
                log.warning("OpenRouter provider error: %s", exc)

        # 2. Gemini Flash (fallback)
        if settings.llm_use_gemini:
            try:
                from .gemini_client import GeminiClient

                gemini = GeminiClient(api_key=settings.llm_gemini_api_key)
                if gemini.initialize():
                    self._providers.append(gemini)
                    log.info("Gemini provider initialized: %s", settings.llm_gemini_model)
                else:
                    log.warning("Gemini provider failed to initialize")
            except Exception as exc:
                log.warning("Gemini provider error: %s", exc)

    def generate_intent(self, transcript: str) -> Dict[str, Any]:
        """
        Generate intent using the best available provider with automatic fallback.

        Tries providers in order, falls back on failure.
        Logs which provider was used.
        """
        if not self._initialized:
            self.initialize()

        if not self._providers:
            log.debug("No LLM providers available")
            return None

        for provider in self._providers:
            if not provider.is_available:
                continue

            try:
                log.debug("Trying provider: %s", provider.name)
                result = provider.generate_intent(transcript)
                self._current_provider = provider
                log.info("Intent generated by %s: %s", provider.name, result)
                return result

            except Exception as exc:
                log.warning("Provider %s failed: %s, trying next...", provider.name, exc)
                # Mark provider as unhealthy
                provider._initialized = False
                continue

        # All providers failed
        log.error("All LLM providers failed, returning unknown intent")
        return {"intent": "unknown", "action": "none"}

    def health_check_all(self) -> Dict[str, bool]:
        """Check health of all providers."""
        results = {}
        for provider in self._providers:
            results[provider.name] = provider.health_check()
        return results

    def get_current_provider(self) -> Optional[str]:
        """Get name of last successful provider."""
        return self._current_provider.name if self._current_provider else None

    def get_available_providers(self) -> List[str]:
        """Get list of available provider names."""
        return [p.name for p in self._providers if p.is_available]

    def get_all_providers(self) -> List[str]:
        """Get list of all provider names (including unavailable)."""
        return [p.name for p in self._providers]

    def set_dev_mode(self, dev_mode: bool) -> None:
        """Switch between dev and prod mode (reinitializes)."""
        if self._dev_mode != dev_mode:
            self._dev_mode = dev_mode
            self._initialized = False
            self._providers.clear()


# Global manager instance
_manager: Optional[LLMManager] = None


def get_llm_manager(dev_mode: bool = True) -> LLMManager:
    """Get global LLM manager instance."""
    global _manager
    if _manager is None:
        _manager = LLMManager(dev_mode=dev_mode)
    return _manager